-- Execute este arquivo uma única vez no SQL Editor do Supabase.
-- Ele cria o controle de pedidos e o resumo semanal do painel.

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  status text not null default 'pending' check (status in ('pending', 'completed', 'not_completed')),
  total numeric(10, 2) not null check (total >= 0),
  items jsonb not null default '[]'::jsonb check (jsonb_typeof(items) = 'array'),
  note text not null default '',
  created_at timestamptz not null default now(),
  completed_at timestamptz,
  updated_at timestamptz not null default now()
);

create index if not exists orders_status_created_at_index on public.orders (status, created_at desc);
create index if not exists orders_created_at_index on public.orders (created_at desc);

alter table public.orders enable row level security;

drop policy if exists "Store admins manage orders" on public.orders;
create policy "Store admins manage orders"
on public.orders for all to authenticated
using (public.is_store_admin())
with check (public.is_store_admin());

create or replace function public.create_store_order(order_items jsonb, order_total numeric, order_note text default '')
returns public.orders
language plpgsql
security definer
set search_path = public
as $$
declare
  new_order public.orders;
begin
  if jsonb_typeof(order_items) <> 'array' or jsonb_array_length(order_items) = 0 then
    raise exception 'O pedido precisa ter pelo menos um item.';
  end if;

  if order_total < 0 then
    raise exception 'O total do pedido não pode ser negativo.';
  end if;

  insert into public.orders (items, total, note)
  values (order_items, order_total, coalesce(order_note, ''))
  returning * into new_order;

  return new_order;
end;
$$;

grant execute on function public.create_store_order(jsonb, numeric, text) to anon, authenticated;

-- Atualiza imediatamente o cache da API após criar a função de pedidos.
notify pgrst, 'reload schema';
