-- Execute este arquivo uma única vez no SQL Editor do Supabase.
-- Cria as avaliações enviadas pelos clientes.

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  rating smallint not null check (rating between 1 and 5),
  message text not null default '' check (char_length(message) <= 500),
  created_at timestamptz not null default now()
);

create index if not exists reviews_created_at_index on public.reviews (created_at desc);

alter table public.reviews enable row level security;

drop policy if exists "Store admins manage reviews" on public.reviews;
create policy "Store admins manage reviews"
on public.reviews for all to authenticated
using (public.is_store_admin())
with check (public.is_store_admin());

create or replace function public.create_store_review(review_rating smallint, review_message text default '')
returns public.reviews
language plpgsql
security definer
set search_path = public
as $$
declare
  new_review public.reviews;
begin
  if review_rating < 1 or review_rating > 5 then
    raise exception 'A avaliação precisa ter entre 1 e 5 estrelas.';
  end if;

  if char_length(coalesce(review_message, '')) > 500 then
    raise exception 'A mensagem é muito longa.';
  end if;

  insert into public.reviews (rating, message)
  values (review_rating, btrim(coalesce(review_message, '')))
  returning * into new_review;

  return new_review;
end;
$$;

grant execute on function public.create_store_review(smallint, text) to anon, authenticated;

-- Garante que as novas funções apareçam na API imediatamente.
notify pgrst, 'reload schema';
