window.GUSTAVO_CATALOG = {
  orderOptions: {
    meal: {
      proteins: ["Frango", "Bisteca", "Calabresa"],
      groups: [
        { id: "rice", title: "Arroz", orderLabel: "Arroz", rule: "required-one", hint: "escolha 1", options: ["Arroz branco", "Arroz temperado"] },
        { id: "beans", title: "Feijão", orderLabel: "Feijão", rule: "optional-one", hint: "escolha no máximo 1", emptyLabel: "Sem feijão", options: ["Feijão tropeiro", "Feijão de caldo"] },
        { id: "pasta", title: "Macarrão", orderLabel: "Macarrão", rule: "optional-many", hint: "opcional", options: ["Macarrão espaguete"] },
        { id: "salad", title: "Saladas", orderLabel: "Salada", rule: "optional-one", hint: "escolha no máximo 1", emptyLabel: "Sem salada", options: ["Vinagrete", "Salada de maionese", "Salada simples (alface, tomate e cebola)"] },
        { id: "extra", title: "Extras", orderLabel: "Extra", rule: "optional-one", hint: "escolha no máximo 1", emptyLabel: "Sem extra", options: ["Purê de batata", "Legumes refogados: batata e cenoura refogadas no alho e na cebola, com uma pitada de orégano"] },
      ],
    },
    drinks: {
      juiceFlavors: ["Maracujá", "Goiaba", "Acerola", "Laranja"],
      vitaminFlavors: ["Banana", "Abacate", "Mamão"],
    },
  },
  products: [
    { id: 1, name: "Pastel de Frango", category: "Salgados", price: 3, detail: "Crocante e feito na hora", badge: "Favorito", image: "assets/products/pastel-autoral.jpg" },
    { id: 2, name: "Pastel de Frango com Catupiry", category: "Salgados", price: 3, detail: "Recheio cremoso", image: "assets/products/pastel-autoral.jpg" },
    { id: 3, name: "Pastel de Calabresa com Queijo", category: "Salgados", price: 3, detail: "Sabor marcante", image: "assets/products/pastel-autoral.jpg" },
    { id: 4, name: "Pastel de Queijo", category: "Salgados", price: 3, detail: "Queijo derretendo", image: "assets/products/pastel-autoral.jpg" },
    { id: 5, name: "Pastel Misto", category: "Salgados", price: 3, detail: "Presunto e queijo", image: "assets/products/pastel-autoral.jpg" },
    { id: 6, name: "Pastel de Bacon com Queijo", category: "Salgados", price: 3, detail: "Bem recheado", image: "assets/products/pastel-autoral.jpg" },
    { id: 7, name: "Pastel de Charque com Queijo", category: "Salgados", price: 3, detail: "Sabor nordestino", image: "assets/products/pastel-autoral.jpg" },
    { id: 8, name: "Pastel de Carne", category: "Salgados", price: 3, detail: "Carne bem temperada", image: "assets/products/pastel-autoral.jpg" },
    { id: 9, name: "Pastel Romeu e Julieta", category: "Salgados", price: 3, detail: "Queijo e goiabada", image: "assets/products/pastel-autoral.jpg" },
    { id: 10, name: "Coxinha de Frango", category: "Salgados", price: 3, detail: "Massa macia e crocante", image: "assets/products/coxinha-autoral.jpg" },
    { id: 11, name: "Coxinha de Carne", category: "Salgados", price: 3, detail: "Recheio caseiro", image: "assets/products/coxinha-autoral.jpg" },
    { id: 12, name: "Enroladinho de Salsicha", category: "Salgados", price: 3, detail: "Perfeito para o lanche", image: "assets/products/stock-pastel.jpg" },
    { id: 13, name: "Cachorro-Quente", category: "Lanches", price: 10, detail: "Lanche completo", image: "assets/products/cachorro-quente.jpg" },
    { id: 14, name: "Hambúrguer", category: "Lanches", price: 8, detail: "Feito com carinho", image: "assets/products/hamburguer-autoral.jpg" },
    { id: 15, name: "Eggs", category: "Lanches", price: 12, detail: "Para matar a fome", image: "assets/products/hamburguer-autoral.jpg" },
    { id: 16, name: "X-Frango", category: "Lanches", price: 13, detail: "Frango saboroso", image: "assets/products/x-egg.jpg" },
    { id: 17, name: "Misto Quente", category: "Lanches", price: 7, detail: "Clássico e quentinho", image: "assets/products/stock-misto.jpg" },
    { id: 18, name: "Pão com Ovo", category: "Lanches", price: 6, detail: "Simples e gostoso", image: "assets/products/x-egg.jpg" },
    { id: 19, name: "Sanduíche Natural", category: "Lanches", price: 6, detail: "Leve e fresquinho", image: "assets/products/stock-natural.jpg" },
    { id: 20, name: "Pão com Manteiga", category: "Lanches", price: 4, detail: "Na chapa", image: "assets/products/stock-misto.jpg" },
    { id: 21, name: "Quentinha · 1 proteína", category: "Quentinhas", price: 15, detail: "Escolha proteína e acompanhamentos", badge: "Almoço", custom: { type: "meal", proteinCount: 1 }, image: "assets/products/quentinha-frango.jpg" },
    { id: 22, name: "Quentinha · 2 proteínas", category: "Quentinhas", price: 20, detail: "Escolha proteínas e acompanhamentos", custom: { type: "meal", proteinCount: 2 }, image: "assets/products/quentinha-frango.jpg" },
    { id: 23, name: "Quentinha · 3 proteínas", category: "Quentinhas", price: 25, detail: "Escolha proteínas e acompanhamentos", custom: { type: "meal", proteinCount: 3 }, image: "assets/products/quentinha-calabresa.jpg" },
    { id: 24, name: "Suco · 400 ml", category: "Bebidas", price: 5, detail: "Escolha seu sabor", custom: { type: "flavor", flavors: ["Maracujá", "Goiaba", "Acerola", "Laranja"], label: "sabor do suco" }, image: "assets/products/stock-juice.jpg" },
    { id: 25, name: "Suco · 500 ml", category: "Bebidas", price: 6, detail: "Escolha seu sabor", custom: { type: "flavor", flavors: ["Maracujá", "Goiaba", "Acerola", "Laranja"], label: "sabor do suco" }, image: "assets/products/stock-juice.jpg" },
    { id: 26, name: "Suco · 1 litro", category: "Bebidas", price: 12, detail: "Escolha seu sabor", custom: { type: "flavor", flavors: ["Maracujá", "Goiaba", "Acerola", "Laranja"], label: "sabor do suco" }, image: "assets/products/stock-juice.jpg" },
    { id: 27, name: "Vitamina · 500 ml", category: "Bebidas", price: 7, detail: "Escolha seu sabor", custom: { type: "flavor", flavors: ["Banana", "Abacate", "Mamão"], label: "sabor da vitamina" }, image: "assets/products/stock-vitamina.jpg" },
    { id: 28, name: "Lasanha Bolonhesa · 250 g", category: "Lasanhas", price: 10, detail: "Carne bovina e massa artesanal", badge: "Caseira", image: "assets/products/stock-lasanha.jpg" },
    { id: 29, name: "Lasanha Bolonhesa · 500 g", category: "Lasanhas", price: 20, detail: "Carne bovina e massa artesanal", image: "assets/products/stock-lasanha.jpg" },
    { id: 30, name: "Lasanha Bolonhesa · 750 g", category: "Lasanhas", price: 25, detail: "Carne bovina e massa artesanal", image: "assets/products/stock-lasanha.jpg" },
    { id: 31, name: "Lasanha de Frango · 250 g", category: "Lasanhas", price: 9, detail: "Frango e massa artesanal", image: "assets/products/stock-lasanha.jpg" },
    { id: 32, name: "Lasanha de Frango · 500 g", category: "Lasanhas", price: 18, detail: "Frango e massa artesanal", image: "assets/products/stock-lasanha.jpg" },
    { id: 33, name: "Lasanha de Frango · 750 g", category: "Lasanhas", price: 23, detail: "Frango e massa artesanal", image: "assets/products/stock-lasanha.jpg" },
  ],
};
